### PR TITLE
abolish nse

### LINKED ISSUE #268: Get rid of nse()
because it doesn't serve any purpose.

### PR DESCRIPTION
**Pull request by TSchiefer**
closes #268

### CODE REVIEW

**Comment by TSchiefer** [comment]
Merge conflicts resolved

**Comment by krlmlr** [comment]
Will there be merge conflicts with the other open pull requests? Verify by merging this branch into the PR branch.

**Comment by TSchiefer** [comment]
Highly likely (this PR touches a lot of different files), but nothing that can't be resolved easily. I think this is the second to last PR for this milestone anyway

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
