### PR TITLE
Added copy_to and compute documentation

### PR DESCRIPTION
**Pull request by jawond**
@krlmlr Changes are at the bottom of the document. It will need some example code.

### CODE REVIEW

**Comment by krlmlr** [comment]
Can you please move this content to #309?

**Comment by krlmlr** [comment]
I see we're still missing example code here. Can you please keep the FIXME so I can add code later if necessary?

**Comment by krlmlr** [comment]
Should this remain here? Do we need to synchronize with `dm-db.Rmd`?

**Comment by jawond** [comment]
> Should this remain here? Do we need to synchronize with `dm-db.Rmd`?

This has been moved to dm-db.Rmd in my local dm-db branch, which is part of the larger document consolidation.

**Comment by krlmlr** [comment]
Now part of howto-dm-db.Rmd.

**Pull request closed without merging**
